### ISSUE TITLE
get_completed_tasks() gives errors.

### ISSUE THREAD

**Issue by notbalanced** [Garee/pytodoist#11]
Hi,
I'm trying to use the call `user.get_completed_tasks()` or `project.get_completed_tasks()` and I get the following error:
```
    tasks = user.get_completed_tasks()
  File "C:\Util\Python27\lib\site-packages\pytodoist\todoist.py", line 529, in get_completed_tasks
    return list(itertools.chain.from_iterable(tasks))
  File "C:\Util\Python27\lib\site-packages\pytodoist\todoist.py", line 528, in <genexpr>
    tasks = (p.get_completed_tasks() for p in self.get_projects())
  File "C:\Util\Python27\lib\site-packages\pytodoist\todoist.py", line 1074, in get_completed_tasks
    tasks_json = response_json['Items']
KeyError: 'Items'
```
I looked at the response_json and found there was an `items`, but not an `Items` (i.e. without a capital "I") and so I changed the code to that.

When I did, I now get the following error:
```
    tasks = p.get_completed_tasks()
  File "C:\Util\Python27\lib\site-packages\pytodoist\todoist.py", line 1077, in get_completed_tasks
    tasks += [self.owner.tasks[task['id']] for task in tasks_json]
KeyError: 175883442
```
That number is the id of one of my tasks. In fact, the first task in the `response_json`.

Do you have any idea what the problem might be?

Thanks!

**Comment by Garee** [comment]
I think you are using an old version of pytodoist as https://github.com/Garee/pytodoist/commit/0821c2863390d1be696b71d99b80647105cc8432 fixed the `items` issue previously.

Can you please try upgrading and see if the second issue persists?

**Comment by notbalanced** [comment]
Sorry about that. I should've made sure that I had the latest version. That did the trick.

Thanks!

(BTW, thanks for putting this together. It really makes a very easy programmatic interface to todoist.)

**Comment by Garee** [comment]
No problem. Sometimes issues like that come up as the Todoist team change their API and I won't know about it until it breaks something. For example, they changed `Items` to `items`.
