### ISSUE TITLE
Completing recurring task terminates task

### ISSUE THREAD

**Issue by ryqiem** [Garee/pytodoist#13]
Hi Garee! Thanks a lot for this!

According to the todoist API, recurring tasks are a [special case](https://developer.todoist.com/v6/#complete-a-recurring-task).

The [complete function](http://pytodoist.readthedocs.io/en/latest/modules.html?highlight=add_task#pytodoist.todoist.Task.complete) terminates the recurring task.

Is it possible for this behaviour to be changed? 👍

**Comment by Garee** [comment]
Thanks for letting me know about this special case. The Todoist API has changed since my initial implementation.

I have created v2.0.5 that contains the necessary change. Please upgrade:

`$ pip install --upgrade pytodoist`

**Comment by ryqiem** [comment]
Thanks a lot Gary! I'm seriously impressed by your turn-around time.

Do you plan to update pytodoist for the todoist API v7? 

I don't want to implement pytodoist into too many scripts in case Todoist abandons v6 ;)

**Comment by Garee** [comment]
PyTodoist is using the latest API, version 6. I haven't heard of any plans to release another version with breaking changes. What I meant was that particular API call had changed to introduce the special case.

You should be fine to go ahead and use the current version. Let me know if you encounter any issues :)

**Comment by Garee** [comment]
I have unit tests for the current functionality so I'm confident that any changes that were made to the API do not break compatibility. It's likely that there are a few new API calls that I haven't added to PyTodoist - I'll go through the documentation later.

If you spot any issues let me know :)

**Comment by ryqiem** [comment]
Glad to hear it! Thanks again 👍
