### ISSUE TITLE
Labels don't work in todoist API v6 wrapper

### ISSUE THREAD

**Issue by ryqiem** [Garee/pytodoist#14]
Hi again!

`label = user.get_label('fokus').id` returns `136167` however

`response = api.add_item(user_api_token, task.content, project_id=output_id, date_string=task.due_date, priority=task.priority, labels=[136167])`

gives me a task without a label. I'm guessing the labels parameter is not passed properly?

Thanks for maintaining this project!

Martin

**Comment by Garee** [comment]
The Todoist API is expecting the labels list as a string. Try: 

```python
labels=str([136167])
```

**Comment by ryqiem** [comment]
Well, that's embarrassing! Thanks a lot 👍
