### ISSUE TITLE
Copying tasks – the easiest way?

### ISSUE THREAD

**Issue by ryqiem** [Garee/pytodoist#15]
Sorry for posting this as an issue, and feel free to mark it complete if you don't have time to look into it.

I'm basically trying to copy a task to another project, if the due date is today. This is what I have so far:

```
def copy_due(inp, outp):
    #Setup projects
    output_id = user.get_project(outp).id
    due_tasks = user.get_project(inp).get_uncompleted_tasks()

    for task in due_tasks:
        if task.due_date is not None:
            date_object = datetime.strptime(task.due_date, '%a %d %b %Y %H:%M:%S %z').date()

            if today_object == date_object:
                notes = task.get_notes() #I have yet to implement notes

                label_ids = task.labels

                response = api.add_item(user_api_token, task.content, project_id=output_id, date_string=task.due_date, priority=task.priority, labels=label_ids)

                task.complete()

            else:
                print("Dates don't match :(")

copy_due("Test", "Inbox")
```

Is there an easier way of doing this?

Also, the labels don't work yet, but I've added an issue for that separately.

Regards!
Martin

**Comment by Garee** [comment]
You can simplify this by using the [search_tasks](http://pytodoist.readthedocs.io/en/latest/modules.html#pytodoist.todoist.User.search_tasks) and [move](http://pytodoist.readthedocs.io/en/latest/modules.html#pytodoist.todoist.Task.move) functions.

For example:

```python
#!/usr/bin/env python

from pytodoist import todoist


def copy_due(user, inp, outp):
    from_project = user.get_project(inp)
    to_project = user.get_project(outp)
    tasks_due_today = user.search_tasks(todoist.Query.TODAY)
    tasks = filter(lambda t: t.project_id == from_project.id, tasks_due_today)
    for task in tasks:
        task.move(to_project)


if __name__ == "__main__":
    username = "john.doe@gmail.com"
    password = "pas55W0rd"
    user = todoist.login(username, password)
    copy_due(user, "From", "To")
```

As this moves the entire task, the notes should also move over and the labels should no longer be an issue.

**Comment by Garee** [comment]
If you don't want to move the task, your approach looks fine as I don't think there is a shorter way to copy. However, I would still use `search_tasks`.

**Comment by ryqiem** [comment]
Your method is way more elegant! However, seeing as I have a working prototype and I'm a tinkerer at best with not much time on my hands, is there any reason I should modify it? 😊

**Comment by Garee** [comment]
You don't need to change your code if does what you want it to. It could be simpler but if it works, it works!

**Comment by ryqiem** [comment]
Awesome! I was wondering whether it might hit the todoist servers with an excessive amount of requests, but as I see it it gets the tasks I need and nothing more.

Thanks a lot for your help! Programmers like you empower noobs like me :)

**Comment by Garee** [comment]
No problem! If you have any more questions feel free to re-open this issue.
