### ISSUE TITLE
HTTP request limits

### ISSUE THREAD

**Issue by ryqiem** [Garee/pytodoist#18]
Hi Garee!

First of all, do you happen to have a donate button? Your script and support has been tremendously helpful for me, so I'd like to make a small contribution to your or the project.

Secondly, I'm currently hitting the request limit of 50 sync requests per minute with the following code:
```python
def copy_due(inp, outp):
    """
    Takes arguments
    inp: Input project
    outp: Output project

    and copies due tasks from inp to outp

    If task has tag with label_id == 691486, it copies the task to a seperate project.
    """
    #Setup projects
    due_tasks = user.get_project(inp).get_uncompleted_tasks()

    i = 1 # Iterator-variable for log

    for task in due_tasks:
        output_id = user.get_project(outp).id
        if task.due_date_utc is not None:
            # print(task.due_date_utc)
            date_object = datetime.strptime(task.due_date_utc, '%a %d %b %Y %H:%M:%S %z').date()

            if today_object == date_object:
                notes = task.get_notes()
                label_ids = task.labels

                # Sets output_id to Someday/maybe solitary project, if task has @someday
                for label_id in label_ids:
                    if label_id == 691486:
                        output_id = user.get_project("Someday-Inbox").id
                        print("This task has labels {label_ids}".format(label_ids=label_ids))

                response = api.add_item(user_api_token, task.content, project_id=output_id, priority=task.priority, labels=str(label_ids))
                print("Moved task {i}".format(i=i))

                task.complete()

                print("Completed task {i}".format(i=i))
                i += 1
    print("Finished project {project}".format(outp))

# Ticklers
copy_due("Recurrent-tickler", "Solitary-actionable")
```

if the input project has more than 50 due tasks. Right now my solution is to add an 
```python    
time.sleep(60) # Sleep for 60 seconds to avoid breaching the 50 requests/min limit from todoist API
```
at the end of the function and to seperate any projects with more than 50 tasks into subprojects, but that seems hacky and doesn't scale very well.

Is there any way for the API to either:
a. Monitor the amount of sync requests and initiate sleep if the frequency of requests is approaching Todoist limits
b. Batch the requests

Thanks!
Martin

**Comment by Garee** [comment]
Hello Martin,

The Todoist API [does](https://developer.todoist.com/#write-resources) support batch requests. However, I haven't added support for this in the higher level abstractions provided by the PyTodoist `todoist` module.

If you want more control you could have a look at the `api` module and call the `sync` function directly.

For your use case I suggest you rate limit the `sync` function to <= 50 calls per minute in the following manner:

```python
# Add to the top of your code before you start using the API.

# Decorator to limit a function call to X per second.
# Credit: http://blog.gregburek.com/2011/12/05/Rate-limiting-with-decorators/
def rate_limit(maxPerSecond):
    minInterval = 1.0 / float(maxPerSecond)
    
    def decorate(func):
        lastTimeCalled = [0.0]
        
        def rateLimitedFunction(*args, **kargs):
            elapsed = time.clock() - lastTimeCalled[0]
            leftToWait = minInterval - elapsed
            if leftToWait > 0:
                time.sleep(leftToWait)
            ret = func(*args, **kargs)
            lastTimeCalled[0] = time.clock()
            return ret
 
        return rateLimitedFunction
    return decorate

# The normal sync function
sync = todoist.API.sync

# The rate limited version of the sync function
@rate_limit(0.8)  # 50/60 = 0.833...
def rate_limited_sync(*args):
    print("Syncing...")
    return sync(*args)

# Use the rate limited sync function
todoist.API.sync = rate_limited_sync
```

>  do you happen to have a donate button?

I don't, but I would appreciate any donation made to [one](https://www.crohnsandcolitis.org.uk/get-involved/donate) of [these](https://supporters.eff.org/donate) [charities](https://www.trusselltrust.org/make-a-donation/). Thank you!

**Comment by ryqiem** [comment]
Thank you, Garee! 

I made a donation to the Trussell trust in your name. 

Have a good one 👍

**Comment by Garee** [comment]
Thanks @ryqiem!
