### ISSUE TITLE
Do not display in order for todoist.Query.TODAY

### ISSUE THREAD

**Issue by mturu1976** [Garee/pytodoist#26]
Recently use pytodoist.

I am coding function to print with the query of today, but there is not sort of order in todoist's application.

```
def today():
    user = todoist.login_with_api_token(API_TOKEN)
    project = user.search_tasks(todoist.Query.TODAY)
    for task in project:
        print(task.content)
        
if __name__ == '__main__':
    today()
```

**Comment by Garee** [comment]
Hi @mturu1976 

I don't think the `search_tasks` function returns the tasks in the same order as they appear in the 'Today' view on the web application.

If you inspect the `item_order` attribute you can see that they are returned in ascending order, it just doesn't match the Today view.

**Comment by mturu1976** [comment]
I see.
It is impossible because there is no function to display in order with todoist.
I'm give Up.
Thank you for your reply
