### ISSUE TITLE
Impossible (?) to get project notes

### ISSUE THREAD

**Issue by Schnatterowski** [Garee/pytodoist#29]
calling get_notes() on a project instance returns a list of all notes of all tasks belonging to that project. I would have expected it to return a list of notes attached to the project itself.

**Comment by Schnatterowski** [comment]
Is there a way to get a user object by giving the user id?

**Comment by Garee** [comment]
Hey @Schnatterowski, I have implemented `get_notes()` in the way you described, but I will also look into adding a way to get the notes for the project itself.

> Is there a way to get a user object by giving the user id?

You can [login with your api_token](https://pytodoist.readthedocs.io/en/latest/modules.html#pytodoist.todoist.login_with_api_token):

```python
>>> from pytodoist import todoist
>>> api_token = '423895h23l5hjfdshafasdjkh523'
>>> user = todoist.login_with_api_token(api_token)
>>> print(user.full_name)
John Doe
```

**Comment by Schnatterowski** [comment]
Thanks for considering to add getting project notes, would be very useful for me. I'll open a new case for the user details question, sorry for mixing this in.
