### ISSUE TITLE
How to get user details by user id

### ISSUE THREAD

**Issue by Schnatterowski** [Garee/pytodoist#30]
Is there a way to get a user object by giving the user id? Several objects contain user_id properties (Task.user_id, Task.responsible_uid, Note.posted_uid, ...), it would be useful to get email address and name for a given user_id. 

Is this possible somehow? Thanks.

**Comment by Garee** [comment]
Hi @Schnatterowski,

Unfortunately this isn't possible. The only way to obtain the user object would be to provide some credentials e.g.

[pytodoist.todoist.login](https://pytodoist.readthedocs.io/en/latest/modules.html#pytodoist.todoist.login)
[pytodoist.todoist.login_with_api_token](https://pytodoist.readthedocs.io/en/latest/modules.html#pytodoist.todoist.login_with_api_token)
[pytodoist.todoist.login_with_google](https://pytodoist.readthedocs.io/en/latest/modules.html#pytodoist.todoist.login_with_google)
