### ISSUE TITLE
Due dates are always AM

### ISSUE THREAD

**Issue by 1minus1** [Garee/pytodoist#5]
I am importing items from my calendar as tasks in Todoist using Workflow and calling a script running in Pythonista, where pytodoist is installed.

Here's a snippet of my code. 

for line in newtasks:
	newtaskname=line.split('@')[0]
	newtaskdate='today @ '+line.split('@')[1]
	print(newtaskdate)
	task=project.add_task(newtaskname,date=newtaskdate,priority=todoist.Priority.LOW

If one of the lines in newtasks is "Meeting@2:00 PM", newtaskname is "Meeting ", newtaskdate is "today @ 2:00 PM", and the task is made fine. In Todoist, however, it the event shows up as being due at 2:00 AM.

**Comment by Garee** [comment]
This issue is occurring due to the way Todoist parses the date string - it doesn't accept an uppercase "PM".

```python
>>> inbox = user.get_project('Inbox')
>>> task_1 = inbox.add_task('Task 1', date='today @ 2:00 PM')
>>> task_2 = inbox.add_task('Task 2', date='today @ 2:00 pm')
>>> print(task_1.content, task_1.due_date)
Task 1 Fri 16 Jan 2015 02:00:00 +0000
>>> print(task_2.content, task_2.due_date)
Task 2 Fri 16 Jan 2015 14:00:00 +0000
```

Please check out the documentation on the supported date/time strings: https://todoist.com/Help/timeInsert

**Comment by 1minus1** [comment]
Thanks! I can now work around this.
