### ISSUE TITLE
Support API v6 :)

### ISSUE THREAD

**Issue by amix** [Garee/pytodoist#7]
Please check out our new API: https://developer.todoist.com/

Awesome work btw. on this!

**Comment by Garee** [comment]
Thanks! I didn't even know this existed. I'll add support for v6 in a new release.

Awesome work on Todoist!

**Comment by amix** [comment]
Thanks Garee!

And awesome to see that you are so active :)

Best regards
Amir

**Comment by Garee** [comment]
API v6 is now used in v2.0.0.

**Comment by amix** [comment]
Awesome work Garee!
