### ISSUE TITLE
get_completed_tasks Premium only?

### ISSUE THREAD

**Issue by chris30o0** [Garee/pytodoist#9]
Edit:
Issue solved.
I had the script running on my old server simultaneously so todoist obviously has a problem with two servers using this at the same time.

**Comment by Garee** [comment]
Closing this issue as @chris30o0 has resolved the problem. Thanks for the report.

**Comment by chris30o0** [comment]
Unfortunately I had a different issue in mind when editing my issue - meaning it is not actually resolved.
Is there a way I could restore my post / should I create a new one?
Maybe you got an email with the text I originally posted so I won't have to type it again, though it's not a lot :P

**Comment by Garee** [comment]
Re-opening as the original issue is still a problem.

**Comment by chris30o0** [comment]
Alright, thanks for reopening.
This is my script which reads all completed tasks in the specified project and writes them to a local file. This does work on one server but not on another.
```
#!/usr/bin/env python
import sys
import time
import subprocess
from pytodoist import todoist
api_token = 'mytokenhere'
user = todoist.login_with_api_token(api_token)
f = open('/root/scripts/tmp1', 'a')
torrents = user.get_project('Torrents')
completed_tasks = torrents.get_completed_tasks()
for task in completed_tasks:
        if task.content:
                f.write(task.content)
                f.write('\n')
                task.delete()
```
Here is the error code I get when running it on - let's call it - Server B
```
# ./todoist_get.py 
Traceback (most recent call last):
  File "./todoist_get.py", line 10, in <module>
    completed_tasks = torrents.get_completed_tasks()
  File "/usr/local/lib/python2.7/dist-packages/pytodoist/todoist.py", line 1071, in get_completed_tasks
    _fail_if_contains_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/pytodoist/todoist.py", line 175, in _fail_if_contains_errors
    raise RequestError(response)
pytodoist.todoist.RequestError: {"error_tag":"PREMIUM_ONLY","error_code":32,"error_extra":{},"error":"Premium only feature"}
```
Any idea on why this is happening on one server but not on another?
Both are running Ubuntu 14.04.3 with python 2.7.6

**Comment by Garee** [comment]
Just to be sure - are you using the same Todoist account on both servers? The `get_completed_tasks` method should only raise that exception if the user is not subscribed to Todoist premium.

**Comment by chris30o0** [comment]
I am using the same account and have never had a todoist premium account.

**Comment by Garee** [comment]
I'm really surprised that it works on one server if the associated Todoist account doesn't have a premium subscription membership.

The underlying API call requires that the user be a premium member. See the Todoist developer documentation for this [here](https://developer.todoist.com/#get-all-completed-items).

Unfortunately I don't think there is anything *I* can do here as it's an API limitation. In this case the error is expected.

**Comment by chris30o0** [comment]
Weird indeed.
Is the premium status checked by pytodoist or the API?
Maybe there is a Bug in the API but your Check prevents using it?

**Comment by chris30o0** [comment]
Just checked my pytodoist:
It works on version 1.0.0 which runs on my old server but not on 2.0.2 which for me is a hint it is indeed an issue with your code.

**Comment by Garee** [comment]
Version 1 is using the old (deprecated) Todoist API which may not have the premium restriction. This would explain why it works.

Version 2 onwards uses the latest API (version 6). I've done some debugging and found a couple of issues that cropped up recently so I'll be releasing an update soon. Unfortunately, I still don't think your issue will be fixed as premium *is* required for this API end-point. 

I suggest you install version 1 on the new server in the mean time.

**Comment by chris30o0** [comment]
Too bad.
Simply copied pytodoist from my old to my new server which is working fine now.
So in fact Todoist changed its API, you adjusted pytodoist but the old API still works.
Weird, but since it's working..
Hope they won't shut it down somehow anytime soon.

Thanks for your help!

**Comment by chris30o0** [comment]
Well..
Today Todoist decided to not support the old API anymore so my script won't work anymore.
Since it's not worth 29€ to me I'll find a different way, most likely without pyTodoist.
Thanks for your work on this!

**Comment by Garee** [comment]
Thanks for letting me know. It's a shame you can no longer use the old version.

All the best!
